config/routes.rb
Sandbstorage::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  resources :messages
  resources :photos
  match 'blog' => 'blogs#index', as: "blog"
  match 'blog/:slug' => 'blogs#show', as: "blog_entry"
  match 'about-us' => 'pages#about_us', as: "about_us"

  namespace :admin do
    resources :photos
    resources :blog_entries
  end

  root :to => 'pages#index'

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  self.per_page = 3
  attr_accessible :body, :is_public, :slug, :title

  validates_presence_of :title, :body
  validates_uniqueness_of :title

  scope :public, where(is_public: true)

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name
	
	def url_content
	  url(:content)
	end
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone, :message

  validates_presence_of :name, :email, :phone, :message
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :is_public, :name, :photo_file, :photo_file_cache
  mount_uploader :photo_file, PhotoUploader

  validates_presence_of :name, :photo_file

  scope :public, where(is_public: true)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
end

app/controllers/admin/blog_entries_controller.rb
class Admin::BlogEntriesController < Admin::AdminController

  expose(:blog_entries) { BlogEntry.all }
  expose(:blog_entry)

  def index
  end

  def show
  end

  def new
    blog_entry.is_public = true
  end

  def create
    if blog_entry.save
      redirect_to admin_blog_entries_path, notice: "Blog entry #{blog_entry.title} was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if blog_entry.update_attributes(params[:blog_entry])
      redirect_to admin_blog_entries_path, notice: "Blog entry #{blog_entry.title} was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    blog_entry.destroy
    redirect_to admin_blog_entries_path, notice: "Blog entry #{blog_entry.title} was deleted successfully!"
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::AdminController
  expose(:photos) {Photo.all}
  expose(:photo)

  def index
  end

  def show
  end

  def new
  end

  def create
    if photo.save
      redirect_to admin_photos_path, notice: "Photo was created successfully!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if photo.update_attributes(params[:photo])
      redirect_to admin_photos_path, notice: "Photo was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  expose(:blog_entries) { BlogEntry.public.page(params[:page]).order('created_at DESC') }
  expose(:blog_entry) { BlogEntry.find_by_slug(params[:slug]) }

  def index
  end

  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      MessageMailer.send_message(@message).deliver
      redirect_to new_message_path, notice: "Your message has been sent successfully!"
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about_us
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  expose(:photos) { Photo.public }

  def index
  end

  def show
  end
end

app/helpers/admin/blog_entries_helper.rb
module Admin::BlogEntriesHelper
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def friendly_date(date)
    date.strftime("%B %d %Y")
  end

  def friendly_time(date)
    date.localtime.strftime("%I:%M %p")
  end

  def friendly_date_and_time(date)
    date.localtime.strftime("%I:%M %p on %B %d, %Y")
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/blog_entries/_blog_menu.html.erb
<div class="navbar navbar-inverse subnav" data-top="60">
  <div class="navbar-inner">
    <%= link_to "Blog", admin_blog_entries_path, class: "brand" %>
    <ul class="nav">
      <li><%= link_to "New Blog Entry", new_admin_blog_entry_url %></li>
    </ul>
  </div>
</div>

app/views/admin/blog_entries/_form.html.erb
<%= simple_form_for [:admin, blog_entry] do |f| %>
  <%= f.error_messages %>
  <%= f.input :title, :input_html => {class: "span6"} %>
  <%= f.input :body, :as => :ckeditor, :label => false, :input_html => {:toolbar => 'Full'} %>
  <%= f.input :is_public %>

  <div class="form-actions">
    <%= link_to "Cancel", admin_blog_entries_path, class: "btn" %>
    <div class="pull-right">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/blog_entries/edit.html.erb
<%= render partial: "admin/blog_entries/blog_menu" %>
<h1>Update Blog Entry</h1>

<%= render :partial => 'form' %>

app/views/admin/blog_entries/index.html.erb
<%= render partial: "admin/blog_entries/blog_menu" %>
<h1>Blog Entries</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Created On</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% for blog_entry in blog_entries %>
    <tr>
      <td><%= blog_entry.title %></td>
      <th><%= blog_entry.created_at.localtime %></th>
      <th><%= link_to "Edit", edit_admin_blog_entry_path(blog_entry), class: "btn" %></th>
    </tr>

  <% end %>
  </tbody>
</table>

app/views/admin/blog_entries/new.html.erb
<%= render partial: "admin/blog_entries/blog_menu" %>
<h1>New Blog Entry</h1>

<%= render :partial => 'form' %>

app/views/admin/photos/_form.html.erb
<div class="well">
  <%= simple_form_for [:admin, photo] do |f| %>
    <%= f.error_messages %>
    <%= f.input :name %>
    <%= image_tag(photo.photo_file_url, style: "width: 800px;") if photo.photo_file_url %>
    <%= f.input :photo_file %>
    <%= f.hidden_field :photo_file_cache %>
    <%= f.input :description, input_html: {rows: 3, class: "span6"} %>
    <%= f.input :is_public %>

    <div class="form-actions">
      <%= link_to "Cancel", admin_photos_path, class: "btn" %>
      <div class="pull-right">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/photos/_photo_menu.html.erb
<div class="navbar navbar-inverse subnav" data-top="60">
  <div class="navbar-inner">
    <%= link_to "Photo Gallery", admin_photos_path, class: "brand" %>
    <ul class="nav">
      <li><%= link_to "New Photo", new_admin_photo_url %></li>
    </ul>
  </div>
</div>

app/views/admin/photos/edit.html.erb
<%= render :partial => 'photo_menu' %>

<h1>Update Photo</h1>
<%= render :partial => 'form' %>

app/views/admin/photos/index.html.erb
<%= render :partial => 'photo_menu' %>

<div class="row-fluid">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Name</th>
      <th>Public</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% for photo in photos %>
      <tr>
        <td>
          <%= image_tag photo.photo_file.url, class: "thumbnail", style: "width: 300px;" %>
        </td>
        <td><%= photo.name %></td>
        <td><%= photo.is_public %></td>
        <td>
          <div class="pull-right">
            <%= link_to "Edit", edit_admin_photo_path(photo), class: "btn" %>
            <%= link_to "Delete", admin_photo_path(photo), :method => :delete, confirm: "Are you sure you want to delete #{photo.name}?", class: "btn btn-danger" %>
          </div>
        </td>
      </tr>

    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/photos/new.html.erb
<%= render :partial => 'photo_menu' %>

<h1>New Photo</h1>
<%= render :partial => 'form' %>

app/views/blogs/index.html.erb
<h1>Our Blog</h1>
<div class="row">
  <div class="span12">
    <p>Ski Boat, Recreation Vehicle, and Small Business overflow storage is what we store in our large spacious storage
      units. Learn about how to store your assets in our easy access indoor storage units. If you would like to learn
      more
      about how to contact us, please click on the contact us link. </p>

    <p><%= link_to "Contact Us", new_message_path, class: "btn btn-primary btn-large pull-right" %></p>
  </div>
</div>
<hr/>
<% for blog_entry in blog_entries %>
  <h2><%= link_to blog_entry.title, blog_entry_path(blog_entry.slug)  %>
    <small><%= friendly_date_and_time(blog_entry.created_at) %></small>
  </h2>
  <p><%= raw(blog_entry.body) %></p>
<% end %>

<%= will_paginate blog_entries, :renderer => BootstrapPagination::Rails, :page_links => false %>

<% content_for :javascript do  %>
  <script type="text/javascript">
    $(function(){
      $("#nav_blog").addClass("active");
    });
  </script>
<% end %>

app/views/blogs/show.html.erb
<ul class="breadcrumb">
  <li><%=link_to "Blog", blog_url %> <span class="divider">/</span></li>
  <li class="active"><%= blog_entry.title %></li>
</ul>
<h1><%= blog_entry.title %></h1>
<p><%= raw(blog_entry.body) %></p>

<%= link_to "Back", blog_path, class: "btn btn-primary btn-large" %>

<% content_for :javascript do  %>
  <script type="text/javascript">
    $(function(){
      $("#nav_blog").addClass("active");
    });
  </script>
<% end %>

app/views/messages/new.html.erb
<div class="row">
  <div class="span9">
    <h1>Let's Get Started</h1>

    <p>Getting started is easy. We would like to talk to you to customize your storage solution. Please fill out the
      form below, and send us a message. We'll get in contact with you within one business day. </p>

    <%= simple_form_for @message do |f| %>
      <%= f.input :name %>
      <%= f.input :email, input_html: {class: "span6"} %>
      <%= f.input :phone %>
      <div class="control-group">
        <%= f.label :message, "What are your storage needs?  Questions?" %>
        <div class="control">
          <%= f.input :message do %>
            <%= f.text_area :message, class: "span9", rows: 10 %>
          <% end %>
        </div>
      </div>
      <div class="pull-right">
        <%= f.submit "Get Started", class: "btn btn-primary btn-large" %>
      </div>
    <% end %>
  </div>
  <div class="span3">
    <div class="well">
      <h3>Our Location</h3>
      <address>
        4754 South 500 West<br/>
        Murray, Utah 84065
      </address>
      (801) 281-1908
    </div>
  </div>
</div>
<% content_for :javascript do %>
  <script type="text/javascript">
    $(function () {
      $("#nav_contact_us").addClass("active");
    });
  </script>
<% end %>

app/views/photos/index.html.erb
<h1>Photo Gallery</h1>
<p>What is it like renting from S and B Storage?  Below are some pictures of our facility, what you will find is large storage areas, huge doors, and a friendly staff who will customize your storage solutions for you.</p>
<div id="gallery" data-toggle="modal-gallery" data-target="#modal-gallery">
  <% for photo in photos %>
    <a href="<%= photo.photo_file.small.url%>" title="<%=photo.name%>" rel="gallery"><%= image_tag photo.photo_file.small.url, class:"thumbnail span3" %></a>
  <% end %>
</div>

<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3 class="modal-title"></h3>
  </div>
  <div class="modal-body"><div class="modal-image"></div></div>
  <div class="modal-footer">
    <a class="btn btn-primary modal-next">Next <i class="icon-arrow-right icon-white"></i></a>
    <a class="btn btn-info modal-prev"><i class="icon-arrow-left icon-white"></i> Previous</a>
    <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000"><i class="icon-play icon-white"></i> Slideshow</a>
    <a class="btn modal-download" target="_blank"><i class="icon-download"></i> Download</a>
  </div>
</div>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(function () {
      $("#nav_photo_gallery").addClass("active");
    });
  </script>
<% end %>