config/routes.rb
Sandbstorage::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  resources :messages
  resources :photos
  match 'blog' => 'blogs#index', as: "blog"
  match 'blog/:slug' => 'blogs#show', as: "blog_entry"
  match 'about-us' => 'pages#about_us', as: "about_us"

  namespace :admin do
    resources :photos
    resources :blog_entries
  end

  root :to => 'pages#index'

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  self.per_page = 3
  attr_accessible :body, :is_public, :slug, :title

  validates_presence_of :title, :body
  validates_uniqueness_of :title

  scope :public, where(is_public: true)

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name
	
	def url_content
	  url(:content)
	end
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone, :message

  validates_presence_of :name, :email, :phone, :message
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :is_public, :name, :photo_file, :photo_file_cache
  mount_uploader :photo_file, PhotoUploader

  validates_presence_of :name, :photo_file

  scope :public, where(is_public: true)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  expose(:blog_entries) { BlogEntry.public.page(params[:page]).order('created_at DESC') }
  expose(:blog_entry) { BlogEntry.find_by_slug(params[:slug]) }

  def index
  end

  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      MessageMailer.send_message(@message).deliver
      redirect_to new_message_path, notice: "Your message has been sent successfully!"
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about_us
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  expose(:photos) { Photo.public }

  def index
  end

  def show
  end
end

app/helpers/admin/blog_entries_helper.rb
module Admin::BlogEntriesHelper
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def friendly_date(date)
    date.strftime("%B %d %Y")
  end

  def friendly_time(date)
    date.localtime.strftime("%I:%M %p")
  end

  def friendly_date_and_time(date)
    date.localtime.strftime("%I:%M %p on %B %d, %Y")
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sandbstorage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "S and B Storage", root_path, class: "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li id="nav_photo_gallery"><%= link_to "Photo Gallery", admin_photos_path  %></li>
              <li><%= link_to "Blog", admin_blog_entries_path %></li>

            </ul>
            <ul class="nav pull-right">
              <li>
                <div class="btn-group">
                  <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#">
                    <%= current_user.email %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Update Account", edit_user_registration_path %></li>
                    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                  </ul>
                </div>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="content">
        <div class="row-fluid">
           <div class="span12">
             <% flash.each do |name, msg| %>
               <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                 <a class="close" data-dismiss="alert">&#215;</a>
                 <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
               </div>
             <% end %>
             <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Precision Auto and Truck" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-34791971-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>

</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Precision Auto and Truck", root_path, class: "brand" %>
      <div class="container nav-collapse">
        <ul class="nav pull-right">
          <li id="nav_about_us"><%= link_to "About Us", about_us_path %></li>
          <li id="nav_photo_gallery"><%= link_to "Photo Gallery", photos_path %></li>
          <li id="nav_blog"><%= link_to "Blog", blog_path %></li>
          <li id="nav_contact_us"><%= link_to "Contact Us", new_message_path %></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span12">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <!--/row-->
  </div>
  <!--/content-->
</div>
<!-- /container -->
<footer>
  <div class="container">
    <div class="row">
      <div class="span5">
        <h3>Precision Auto and Truck</h3>
        <p>We are Utah's Auto and Truck maintenance center.   </p>
        <hr />
        <p>&copy; Precision Auto and Truck <%= DateTime.now.year %>. All Rights Reserved.</p>
        <p>Crafted by <%= link_to "NexBusiness", "http://www.nexbusiness.com" %></p>
      </div>
      <div class="span1">&nbsp;</div>
      <div class="span3">
        <h3>Site Map</h3>
        <ul class="unstyled">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About Us", about_us_path %></li>
          <li><%= link_to "Photo Gallery", photos_path %></li>
          <li><%= link_to "Blog", blog_url %></li>
          <li><%= link_to "Contact Us", new_message_url %></li>
        </ul>
      </div>
      <div class="span3">
        <h3>We're Social</h3>
      </div>
    </div>
  </div>

</footer>
<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>
<%= yield :javascript %>
</body>
</html>

app/views/pages/about_us.html.erb
<h1>About Us</h1>

<h2>Our Units</h2>
<p>Our Units are 13ft by 32 ft outside dimensions with the inside dimensions of 12 ft by 30ft 3inches deep. The over head doors are 11ft 6inches high and 10ft 11inches wide.
  The units are perfect for ski boats with towers or recreational vehicles.
  The units are also work will for my small business tenants that store over flow materials for future use</p>
<p><strong>Rental Rate: $175.00 a month</strong></p>

<h2>Our Staff</h2>
<p>My Name is Jon Siddoway. I have been the owner and manager of the Storage unit for twenty-five years. We have a family feel that attracts long term tenants with twenty or more Renter in the same space for ten years or longer.
With a wide turning area for trailers, and a lower rental rates than comparable units helps us to avoid turn over and saves on your budget. </p>

<p>Call me any time if you have questions.  Jon at (801) 573-0479
Or e-mail me at   (sid99us@yahoo.com) </p>


<h2>Our Location</h2>
<address>
  <h3>S and b Storage</h3>
  4754 South 500 West<br />
  Murray, Utah 84065 <br />
  (801) 573-0479
</address>


<% content_for :javascript do  %>
  <script type="text/javascript">
    $(function(){
      $("#nav_about_us").addClass("active");
    });
  </script>
<% end %>

app/views/pages/index.html.erb
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><%= image_tag "slider/front_of_store.jpg" %></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<div class="row">
  <div class="span8">
    <h3>Why Precision Auto and Truck?</h3>
    <p>We are Utah's Mechanic and maintenance solution. </p>
  </div>
  <div class="span4">
    <h3>Contact Us</h3>
    <p>Interested in learning more about how we can be your mechanic and maintenance solutions? </p>
    <%= link_to "Let's get Started", new_message_path, class: "btn btn-primary btn-large" %>
  </div>
</div>